/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TilIndexRouteImport } from './routes/til/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as TilSlugRouteImport } from './routes/til/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TilIndexRoute = TilIndexRouteImport.update({
  id: '/til/',
  path: '/til/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const TilSlugRoute = TilSlugRouteImport.update({
  id: '/til/$slug',
  path: '/til/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/til/$slug': typeof TilSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/til/': typeof TilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/til/$slug': typeof TilSlugRoute
  '/blog': typeof BlogIndexRoute
  '/til': typeof TilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/til/$slug': typeof TilSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/til/': typeof TilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/blog/$slug' | '/til/$slug' | '/blog/' | '/til/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/blog/$slug' | '/til/$slug' | '/blog' | '/til'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog/$slug'
    | '/til/$slug'
    | '/blog/'
    | '/til/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogSlugRoute: typeof BlogSlugRoute
  TilSlugRoute: typeof TilSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  TilIndexRoute: typeof TilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/til/': {
      id: '/til/'
      path: '/til'
      fullPath: '/til/'
      preLoaderRoute: typeof TilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/til/$slug': {
      id: '/til/$slug'
      path: '/til/$slug'
      fullPath: '/til/$slug'
      preLoaderRoute: typeof TilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogSlugRoute: BlogSlugRoute,
  TilSlugRoute: TilSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  TilIndexRoute: TilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
